export { dashboardWidgetQueries } from './dashboardWidgetQueries';
export { userQueries } from './userQueries';
export { organizationQueries } from './organizationQueries';
export { hotelGroupQueries } from './hotelGroupQueries';
export { roleQueries } from './roleQueries';
export { reportQueries } from './reportQueries';
export { incomeJournalExportQuery } from './incomeJournalExportQueries';
export { customTableRowColumnCfgQueries } from './customTableRowColumnCfg';
export { customTableRowColumnQueries } from './customTableRowColumn';
export { healthScoreBoardQueries, healthScorecardQueries, healthScorecardSVPEVPQueries } from './healthScorecard';
