const replacements = {
  hook: [
    'globals',
    'hotel',
    'group',
    'date',
    'fromDate',
    'toDate',
    'download',
    'add',
    'remove',
    'order',
    'search',
    'modes',
    'upload',
    'periodSelector',
    'edit',
    'manualEntry',
    'portfolio',
    'drawer',
    'extraButton1',
    'extraButton2',
    'extraButton3',
  ],
  mainPage: [
    'hotel',
    'group',
    'portfolio',
    'date',
    'fromDate',
    'toDate',
    'goButton',
    'modes',
    'download',
    'upload',
    'addNew',
    'search',
    'order',
    'periodSelector',
    'year',
    'unmappedSelector',
    'buttonDropdown',
    'edit',
    'manualEntry',
    'genericForm',
    'drawer',
    'extraButton1',
    'extraButton2',
    'extraButton3',
  ],
  constants: ['periodSelector', 'modes'],
};

module.exports = {
  replacements,
};
