export const columnsCfg = [
  {
    title: 'Lvl',
    valueTypeId: 5,
    fieldName: 'rewardLevel',
  },
  {
    title: 'Gst',
    valueTypeId: 1,
    fieldName: 'numberOfGuest',
  },
  {
    title: 'Type',
    valueTypeId: 5,
    fieldName: 'roomType',
  },
  {
    title: 'Room',
    valueTypeId: 1,
    fieldName: 'roomIdentifier',
  },
  {
    title: 'S/W',
    valueTypeId: 5,
    fieldName: 'roomSharedWith',
  },
  {
    title: 'Group',
    valueTypeId: 5,
    fieldName: 'groupCode',
  },
  {
    title: 'ArrDt',
    valueTypeId: 5,
    fieldName: 'arrivalDate',
  },
  {
    title: '#Nt',
    valueTypeId: 1,
    fieldName: 'numberOfNight',
  },
  {
    title: 'Deprt',
    valueTypeId: 5,
    fieldName: 'departureDate',
  },
  {
    title: 'Folio',
    valueTypeId: 5,
    fieldName: 'folio',
  },
  {
    title: 'D/B code',
    valueTypeId: 5,
    fieldName: 'settlementCode',
  },
  {
    title: 'ST',
    valueTypeId: 5,
    fieldName: 'settlementType',
  },
  {
    title: 'Outstdg',
    valueTypeId: 2,
    fieldName: 'outstandingAmount',
  },
  {
    title: 'Limit',
    valueTypeId: 2,
    fieldName: 'authorizedLimitAmount',
  },
  {
    title: 'MarshaCode',
    valueTypeId: 5,
    fieldName: 'hotelCode',
  },
  {
    title: 'Variance',
    valueTypeId: 2,
    fieldName: 'variance',
  },
  {
    title: 'I',
    valueTypeId: 5,
    fieldName: 'incidental',
  },
  {
    title: 'Rm Rate',
    valueTypeId: 2,
    fieldName: 'roomRate',
  },
  {
    title: 'Rate Code',
    valueTypeId: 1,
    fieldName: 'rateCode',
  },
  {
    title: 'Confo #',
    valueTypeId: 1,
    fieldName: 'confirmationNumber',
  },
];

export const items = [
  {
    id: '07a73237-434f-4fe5-9cfd-6cac1761a840',
    hotelCode: 'ORFVB',
    hotelId: 549,
    businessDate: '1619827200000',
    rewardLevel: '',
    numberOfGuest: '1.0000',
    roomType: 'HSE',
    roomIdentifier: 'GRP',
    roomSharedWith: '',
    groupCode: 'EVBP',
    arrivalDate: '1646352000000',
    numberOfNight: '3.0000',
    departureDate: '1646352000000',
    folio: 'G3738',
    settlementCode: '',
    outstandingAmount: 0,
    settlementType: 'DB',
    authorizedLimitAmount: 0,
    incidental: '',
    roomRate: '0.000000000000000e+000',
    rateCode: 'HSEA',
    variance: 0,
    confirmationNumber: '0',
    reservationKey: 'ORFVB:2021-05-01:G3738',
    sourceId: 6,
    etlFileName: 'FOSSE_RPT_ORFVB_651SK_2022-05-01_1619874464.txt',
    etlIngestDatetime: '1651849690720',
  },
  {
    id: '0a740fb2-26c9-4622-8703-0f3abab16f6d',
    hotelCode: 'ORFVB',
    hotelId: 549,
    businessDate: '1619827200000',
    rewardLevel: '',
    numberOfGuest: '0.0000',
    roomType: 'HSE',
    roomIdentifier: 'RVS',
    roomSharedWith: '',
    groupCode: '',
    arrivalDate: '1651190400000',
    numberOfNight: '1.0000',
    departureDate: '1651190400000',
    folio: '44976',
    settlementCode: 'EXPEDIA',
    outstandingAmount: 0,
    settlementType: 'DB',
    authorizedLimitAmount: 0,
    incidental: 'I',
    roomRate: '0.000000000000000e+000',
    rateCode: 'HSEA',
    variance: 0,
    confirmationNumber: '0',
    reservationKey: 'ORFVB:2021-05-01:44976',
    sourceId: 6,
    etlFileName: 'FOSSE_RPT_ORFVB_651SK_2022-05-01_1619874464.txt',
    etlIngestDatetime: '1651849690720',
  },
  {
    id: '0e0ecea5-b0a5-4a38-8d9a-5f7c9a575249',
    hotelCode: 'ORFVB',
    hotelId: 549,
    businessDate: '1619827200000',
    rewardLevel: '',
    numberOfGuest: '1.0000',
    roomType: 'HSE',
    roomIdentifier: 'GRP',
    roomSharedWith: '',
    groupCode: 'EVCP',
    arrivalDate: '1642204800000',
    numberOfNight: '3.0000',
    departureDate: '1642204800000',
    folio: 'G3728',
    settlementCode: '',
    outstandingAmount: 0,
    settlementType: 'DB',
    authorizedLimitAmount: 0,
    incidental: '',
    roomRate: '0.000000000000000e+000',
    rateCode: 'HSEA',
    variance: 0,
    confirmationNumber: '0',
    reservationKey: 'ORFVB:2021-05-01:G3728',
    sourceId: 6,
    etlFileName: 'FOSSE_RPT_ORFVB_651SK_2022-05-01_1619874464.txt',
    etlIngestDatetime: '1651849690720',
  },
];

export const hotels = [
  { hotelName: 'Hotel1', id: 1 },
  { hotelName: 'Hotel2', id: 2 },
  { hotelName: 'Hotel3', id: 3 },
  { hotelName: 'Hotel4', id: 4 },
];

export const hotelsGroupsMap = {
  1: { id: 1, groupName: 'Group1', hotels: [hotels[0], hotels[1]] },
  2: { id: 2, groupName: 'Group2', hotels: [hotels[2], hotels[3]] },
};

export const searchColumns = [
  'rewardLevel',
  'numberOfGuest',
  'roomType',
  'roomIdentifier',
  'roomSharedWith',
  'groupCode',
  'arrivalDate',
  'numberOfNight',
  'departureDate',
  'folio',
  'settlementCode',
  'settlementType',
  'hotelCode',
  'incidental',
  'rateCode',
  'confirmationNumber',
  'outstandingAmountSearch',
  'authorizedLimitAmountSearch',
  'varianceSearch',
  'roomRateSearch',
];
