export const DownloadableReportNames = {
  mdoGlCodes: 'Mdo Gl Codes',
  pnlMonthly: 'P&L Monthly',
  pnlYearly: 'P&L Yearly',
  pnlPropertyComp: 'P&L Property Comparision',
  pnlUnmapped: 'P&L Unmapped',
  arMapping: 'AR Mapping',
  aSalesMapping: 'Account Sales Mapping',
  glMapping: 'GL Mapping',
  glCodes: 'GL Codes',
  glHierarchy: 'GL Hierarchy',
  ijMapping: 'IJ Mapping',
  ijSummary: 'IJ Summary',
  ijRecon: 'IJ Recon',
  arDashboard: 'AR Dashboard',
  ar: 'AR',
  pickup: 'Pickup',
  pickupSummary: 'Pickup Summary',
  pickupMonthly: 'Pickup Monthly',
  gssMedaliya: 'GSS Medallia',
  gssByPriority: 'GSS By Priority',
  gssMonth: 'GSS By Month',
  strDefault: 'STR Default',
  strRollup: 'STR Rollup',
  report306090: '30 60 90',
  salesProd: 'Sales Production',
  salesManagement: 'Sales Management',
  accountManagement: 'Account Management',
  purchaseOrder: 'Purchase Order',
  primaryDashboard: 'Primary Dashboard',
  pnlView: 'P&L View',
  missingDates: 'Missing Dates',
  guestLedger: 'Guest Ledger',
};
