version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build:
    docker:
      - image: cimg/node:lts
      
    working_directory: ~/repo
    steps:
      - checkout
      
      - restore_cache:
          keys:
            - v1-devDependencies-{{ checksum "package.json" }}
            - v1-devDependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-devDependencies-{{ checksum "package.json" }}

      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/pip/2.7/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws configure set aws_access_key_id ${AWS_ACCESS_KEY}
      - run: aws configure set aws_secret_access_key ${AWS_SECRET_KEY}
      - run: aws configure set region ${AWS_REGION}
      - run: aws configure set output json
      - run: aws codeartifact login --tool npm --repository ${AWS_REPO} --domain ${AWS_DOMAIN} --domain-owner ${AWS_DOMAIN_OWNER}
      - run: npm run build
      - run: npm publish
      - run: echo \"\" > $(npm config get userconfig)

  test:
    docker:
      - image: cimg/node:lts
      
    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-devDependencies-{{ checksum "package.json" }}
            - v1-devDependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-devDependencies-{{ checksum "package.json" }}

      - run: npm run test
workflows:
  builds:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
